# Configuration de la base de données
spring.datasource.url=jdbc:postgresql://localhost:5432/cinema?charset=UTF-8&useUnicode=true
spring.datasource.username=oceanechristodoulou
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuration JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.connection.characterEncoding=UTF-8
spring.jpa.properties.hibernate.connection.CharSet=UTF-8
spring.jpa.properties.hibernate.connection.useUnicode=true
spring.jpa.properties.hibernate.validator.apply_to_ddl=false
spring.jpa.properties.hibernate.check_nullability=false

# Configuration du serveur
server.port=8080

# Configuration HTTP pour l'encodage UTF-8
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

# Configuration du répertoire d'upload des images
app.upload.dir=${user.home}/cinema-uploads


# Logging
logging.level.com.cinema=INFO
